AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Static Website using CloudFormation Git Sync

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bookworld-website-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub ${WebsiteBucket.Arn}/*

Outputs:
  WebsiteURL:
    Description: S3 Website URL
    Value: !Sub http://${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com
